# Generated by Django 4.0.6 on 2022-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=128)),
                ('client_org', models.CharField(max_length=256)),
                ('bill_number', models.IntegerField()),
                ('date', models.DateField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service', models.TextField()),
            ],
        ),
    ]
